///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsChevron = 'assets/chevron.svg';
  static const String assetsClose = 'assets/close.svg';
  static const String assetsDelete = 'assets/delete.svg';
  static const String assetsEllipse = 'assets/Ellipse 9 (1).svg';
  static const String assetsFlight1 = 'assets/flight1.svg';
  static const String assetsFlight2 = 'assets/flight2.svg';
  static const String assetsFlight3 = 'assets/flight3.svg';
  static const String assetsFlight4 = 'assets/flight4.svg';
  static const String assetsFlight5 = 'assets/flight5.svg';
  static const String assetsGift1 = 'assets/gift1.png';
  static const String assetsGift2 = 'assets/gift2.png';
  static const String assetsHome1 = 'assets/home1.svg';
  static const String assetsHome2 = 'assets/home2.svg';
  static const String assetsInfo = 'assets/info.svg';
  static const String assetsLogout = 'assets/logout.svg';
  static const String assetsOnboard = 'assets/onboard.svg';
  static const String assetsP1 = 'assets/p1.png';
  static const String assetsP10 = 'assets/p10.png';
  static const String assetsP11 = 'assets/p11.png';
  static const String assetsP12 = 'assets/p12.png';
  static const String assetsP2 = 'assets/p2.png';
  static const String assetsP3 = 'assets/p3.png';
  static const String assetsP4 = 'assets/p4.png';
  static const String assetsP5 = 'assets/p5.png';
  static const String assetsP6 = 'assets/p6.png';
  static const String assetsP7 = 'assets/p7.png';
  static const String assetsP8 = 'assets/p8.png';
  static const String assetsP9 = 'assets/p9.png';
  static const String assetsS1 = 'assets/s1.svg';
  static const String assetsS2 = 'assets/s2.svg';
  static const String assetsS3 = 'assets/s3.svg';
  static const String assetsS4 = 'assets/s4.svg';
  static const String assetsS5 = 'assets/s5.svg';
  static const String assetsSettings = 'assets/settings.svg';
  static const String assetsSplash1 = 'assets/splash1.svg';
  static const String assetsSplash2 = 'assets/splash2.svg';
  static const String assetsStatus = 'assets/status.svg';
  static const String assetsTab1 = 'assets/tab1.svg';
  static const String fontsInterBold = 'assets/fonts/Inter-Bold.ttf';
  static const String fontsInterMedium = 'assets/fonts/Inter-Medium.ttf';
  static const String fontsInterRegular = 'assets/fonts/Inter-Regular.ttf';
  static const String statusGroup1 = 'assets/bronze.svg';
  static const String statusGroup3 = 'assets/silver.svg';
  static const String statusGroup4 = 'assets/gold.svg';
}
