name: avia_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  url_launcher:
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  carousel_slider: ^5.0.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/status/
  fonts:
    # Inter
    - family: InterR
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: InterM
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: InterB
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf